# This workflow will do a clean installation of node dependencies, cache/restore them, lint the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: lint and test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
    - run: |
        npm ci
        npm run lint
        npm test
        npm run build